USE [master]
GO
/****** Object:  Database [DB_MenuX]    Script Date: 7/05/2025 11:30:15 p. m. ******/
CREATE DATABASE [DB_MenuX]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_MenuX', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DB_MenuX.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DB_MenuX_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DB_MenuX_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [DB_MenuX] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_MenuX].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [DB_MenuX] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [DB_MenuX] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [DB_MenuX] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [DB_MenuX] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [DB_MenuX] SET ARITHABORT OFF 
GO
ALTER DATABASE [DB_MenuX] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [DB_MenuX] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [DB_MenuX] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [DB_MenuX] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [DB_MenuX] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [DB_MenuX] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [DB_MenuX] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [DB_MenuX] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [DB_MenuX] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [DB_MenuX] SET  ENABLE_BROKER 
GO
ALTER DATABASE [DB_MenuX] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [DB_MenuX] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [DB_MenuX] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [DB_MenuX] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [DB_MenuX] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [DB_MenuX] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [DB_MenuX] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [DB_MenuX] SET RECOVERY FULL 
GO
ALTER DATABASE [DB_MenuX] SET  MULTI_USER 
GO
ALTER DATABASE [DB_MenuX] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [DB_MenuX] SET DB_CHAINING OFF 
GO
ALTER DATABASE [DB_MenuX] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [DB_MenuX] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [DB_MenuX] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [DB_MenuX] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'DB_MenuX', N'ON'
GO
ALTER DATABASE [DB_MenuX] SET QUERY_STORE = ON
GO
ALTER DATABASE [DB_MenuX] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [DB_MenuX]
GO
/****** Object:  Table [dbo].[__EFMigrationsHistory]    Script Date: 7/05/2025 11:30:16 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[__EFMigrationsHistory](
	[MigrationId] [nvarchar](150) NOT NULL,
	[ProductVersion] [nvarchar](32) NOT NULL,
 CONSTRAINT [PK___EFMigrationsHistory] PRIMARY KEY CLUSTERED 
(
	[MigrationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[TodoItems]    Script Date: 7/05/2025 11:30:16 p. m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TodoItems](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](max) NULL,
	[IsComplete] [bit] NULL,
 CONSTRAINT [PK_TodoItems] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
INSERT [dbo].[__EFMigrationsHistory] ([MigrationId], [ProductVersion]) VALUES (N'20250507044017_AddTableTodoItems', N'9.0.4')
GO
SET IDENTITY_INSERT [dbo].[TodoItems] ON 

INSERT [dbo].[TodoItems] ([Id], [Name], [IsComplete]) VALUES (1, N'Menux', 0)
SET IDENTITY_INSERT [dbo].[TodoItems] OFF
GO
USE [master]
GO
ALTER DATABASE [DB_MenuX] SET  READ_WRITE 
GO
